name: Manage EKS Cluster

on:
  workflow_dispatch:
    inputs:
      clusterName:
        description: 'Name of the EKS cluster'
        required: false
        default: 'demo-test-app2-cluster'
      awsRegion:
        description: 'AWS Region for the cluster'
        required: true
      action:
        description: 'Action to perform (apply/destroy)'
        required: true

jobs:
  apply_cluster:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'apply' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.awsRegion }}

      - name: Install eksctl
        run: |
          curl --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin
          eksctl version

      - name: Check if EKS Cluster Exists
        id: check-cluster
        run: |
          if eksctl get cluster --name demo-test-app2-cluster --region ${{ github.event.inputs.awsRegion }}; then
            echo "EKS cluster exists."
            echo "EXISTS=true" >> $GITHUB_ENV
          else
            echo "EKS cluster does not exist."
            echo "EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Create EKS Cluster if Not Exists
        if: env.EXISTS == 'false'
        run: |
          eksctl create cluster --name demo-test-app2-cluster --region ${{ github.event.inputs.awsRegion }} --nodes 2 --managed

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name demo-test-app2-cluster --region ${{ github.event.inputs.awsRegion }}
          kubectl get nodes

      - name: Deploy Application
        run: |
          kubectl apply -f k8s_deployment.yaml
          kubectl get pods

  destroy_cluster:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'destroy' }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.awsRegion }}

      - name: Install eksctl
        run: |
          curl --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz" | tar xz -C /tmp
          sudo mv /tmp/eksctl /usr/local/bin
          eksctl version

      - name: Delete EKS Cluster
        run: |
          eksctl delete cluster --name demo-test-app2-cluster --region ${{ github.event.inputs.awsRegion }}
